// Import: unpack a standalone Claude Design export into plain static files.
//
// A standalone export is self-extracting: every page component, script,
// font, image and video is embedded (gzip + base64) in a JSON manifest that
// the page decodes into blob: URLs on each visit. This script writes each
// embedded file back out under the path the pages reference. public/ was
// created this way from design/Somion Website.html and has been edited by
// hand since, so a new export goes to a scratch folder to be diffed and
// merged, not straight over public/.
//
//   node scripts/unpack.mjs [export.html] [outDir] [--force]

import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import zlib from 'node:zlib';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2).filter((a) => a !== '--force');
const SOURCE = path.resolve(ROOT, args[0] ?? 'design/Somion Website.html');
const OUT = path.resolve(ROOT, args[1] ?? 'design/unpacked');
if (OUT === path.join(ROOT, 'public') && fs.existsSync(OUT) && !process.argv.includes('--force')) {
  throw new Error('public/ holds the hand-edited site. Unpack to a scratch folder and merge, or pass --force to overwrite it.');
}

const GOOGLE_FONTS_CSS = /^https:\/\/fonts\.googleapis\.com\/css2?\?/;
const UNPKG = /^https:\/\/unpkg\.com\/((?:@[^/]+\/)?[^/@]+)@([^/]+)\/(.+)$/;
const FONT_PRECONNECT = /[ \t]*<link rel="preconnect" href="https:\/\/fonts\.(?:googleapis|gstatic)\.com"[^>]*>\r?\n?/g;
const UUID = /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/g;
const EXT_FOR_MIME = { 'text/javascript': 'js', 'application/javascript': 'js', 'text/css': 'css', 'image/svg+xml': 'svg' };

// Every component's own <head> loads ./support.js, the design tool's
// standalone viewer, which the export doesn't ship. The app shell fetches
// components as text and never runs that tag; it only runs when a visitor
// opens a component URL directly ("open link in new tab" on a nav link), so
// this stand-in forwards them to the same page inside the shell's router.
const SUPPORT_JS = `// Generated by scripts/build.mjs: forwards a directly opened component page
// (e.g. Hosting.dc.html?plan=pro#faq) into the app shell's hash router.
(function () {
  var m = /([A-Za-z]+)\\.dc\\.html$/.exec(location.pathname);
  if (m) location.replace('./#/' + m[1] + location.search + (location.hash.length > 1 ? '~' + location.hash.slice(1) : ''));
})();
`;

const warnings = [];

// ── Read the bundle ─────────────────────────────────────────────────
const html = fs.readFileSync(SOURCE, 'utf8');
function island(type) {
  const open = `<script type="__bundler/${type}">`;
  const start = html.indexOf(open);
  if (start < 0) throw new Error(`${path.basename(SOURCE)} has no ${type} block. Is it a standalone design export?`);
  return JSON.parse(html.slice(start + open.length, html.indexOf('</script>', start)));
}
const manifest = island('manifest');
const extResources = island('ext_resources');
let template = island('template');
if (island('page_order').length) throw new Error('This export embeds framed pages (page_order), which this build does not unpack.');

const bytes = {};
for (const [uuid, entry] of Object.entries(manifest)) {
  const raw = Buffer.from(entry.data, 'base64');
  bytes[uuid] = entry.compressed ? zlib.gunzipSync(raw) : raw;
}

// ── Decide where every file goes ────────────────────────────────────
const files = new Map(); // site-relative path -> contents
const pathOf = {}; // manifest uuid -> site-relative path
const hashName = (buf, ext) => crypto.createHash('sha256').update(buf).digest('hex').slice(0, 10) + '.' + ext;
function emit(rel, data) {
  const prev = files.get(rel);
  if (prev !== undefined && !Buffer.from(prev).equals(Buffer.from(data))) throw new Error(`two different files want ${rel}`);
  files.set(rel, data);
  return rel;
}

const uuidFor = {}; // resource id as the pages reference it -> uuid; later entries win, as in the bundler
for (const { id, uuid } of extResources) if (bytes[uuid]) uuidFor[id] = uuid;

const reactUmd = {}; // package -> local path, preloaded ahead of the runtime
const localStylesheet = {}; // external stylesheet URL -> local copy

for (const [id, uuid] of Object.entries(uuidFor)) {
  if (!/^https?:/.test(id)) {
    const rel = path.posix.normalize(id.replace(/^\.\//, ''));
    if (rel.startsWith('../') || path.posix.isAbsolute(rel)) throw new Error(`refusing to write outside the site root: ${id}`);
    pathOf[uuid] = emit(rel, bytes[uuid]);
  } else if (GOOGLE_FONTS_CSS.test(id)) {
    // Self-host the web fonts: move the inlined data: fonts out into files.
    const css = bytes[uuid].toString('utf8').replace(
      /url\((["']?)data:font\/(\w+);base64,([A-Za-z0-9+/=]+)\1\)/g,
      (_, q, type, b64) => {
        const font = Buffer.from(b64, 'base64');
        const name = hashName(font, type);
        emit('fonts/' + name, font);
        return `url("${name}")`;
      },
    );
    if (/url\((["']?)https?:/.test(css)) warnings.push(`${id} still points at remote font files`);
    localStylesheet[id] = emit('fonts/' + hashName(Buffer.from(css), 'css'), css);
  } else if (UNPKG.test(id)) {
    const [, pkg, version, file] = id.match(UNPKG);
    pathOf[uuid] = emit(`vendor/${pkg}@${version}/${file}`, bytes[uuid]);
    if (pkg === 'react' || pkg === 'react-dom') reactUmd[pkg] = pathOf[uuid];
  } else {
    warnings.push(`left on its CDN: ${id}`);
  }
}

// Files only the app shell references by uuid: the runtime and its fonts.
const referencedByExt = new Set(extResources.map((e) => e.uuid));
for (const [uuid, entry] of Object.entries(manifest)) {
  if (pathOf[uuid]) continue;
  if (!template.includes(uuid)) {
    if (!referencedByExt.has(uuid)) warnings.push(`unreferenced ${entry.mime} asset ${uuid} skipped`);
    continue;
  }
  const [kind, subtype] = entry.mime.split('/');
  if (kind === 'font') pathOf[uuid] = emit('fonts/' + hashName(bytes[uuid], subtype), bytes[uuid]);
  else if (/javascript/.test(subtype) && bytes[uuid].toString('utf8', 0, 200).includes('dc-runtime')) pathOf[uuid] = emit('dc-runtime.js', bytes[uuid]);
  else pathOf[uuid] = emit('static/' + hashName(bytes[uuid], EXT_FOR_MIME[entry.mime] ?? subtype.replace(/\W.*/, '')), bytes[uuid]);
}

// ── Rewrite the app shell and components ────────────────────────────
for (const [uuid, rel] of Object.entries(pathOf)) template = template.split(uuid).join(rel);

const fontsLocal = Object.keys(localStylesheet).length > 0;
if (fontsLocal) template = template.replace(FONT_PRECONNECT, '');

// Load React from this origin up front; the runtime then skips its unpkg fallback.
const runtimeTag = '<script src="dc-runtime.js"></script>';
if (!reactUmd.react || !reactUmd['react-dom']) warnings.push('React is not in the bundle; the runtime will load it from unpkg');
else if (!template.includes(runtimeTag)) warnings.push('runtime <script> tag not found; React will load from unpkg');
else template = template.replace(runtimeTag, `<script src="${reactUmd.react}"></script>\n<script src="${reactUmd['react-dom']}"></script>\n${runtimeTag}`);

if (files.has('index.html')) throw new Error('the bundle already contains an index.html');
emit('index.html', template);

for (const [rel, data] of files) {
  if (!rel.endsWith('.dc.html')) continue;
  let src = data.toString('utf8');
  for (const [url, local] of Object.entries(localStylesheet)) {
    for (const form of [url, url.replaceAll('&', '&amp;')]) src = src.split(`href="${form}"`).join(`href="${local}"`);
  }
  if (fontsLocal) src = src.replace(FONT_PRECONNECT, '');
  files.set(rel, src);
}

const needsSupport = [...files].some(([rel, data]) => rel.endsWith('.dc.html') && data.includes('src="./support.js"'));
if (needsSupport && !files.has('support.js')) emit('support.js', SUPPORT_JS);

// ── Sanity checks ───────────────────────────────────────────────────
for (const [rel, data] of files) {
  if (!/\.(html|js|css)$/.test(rel)) continue;
  const stale = (data.toString().match(UUID) ?? []).filter((u) => manifest[u]);
  if (stale.length) throw new Error(`${rel} still references bundle uuid ${stale[0]}`);
}
for (const m of template.matchAll(/<(?:script|link)\b[^>]*\s(?:src|href)="([^"#?:]+)"/g)) {
  if (!files.has(m[1])) throw new Error(`index.html references ${m[1]}, which the build did not produce`);
}

// ── Write ───────────────────────────────────────────────────────────
if (OUT === path.parse(OUT).root || SOURCE.startsWith(OUT + path.sep)) throw new Error(`refusing to clean ${OUT}`);
fs.rmSync(OUT, { recursive: true, force: true });
for (const [rel, data] of files) {
  const dest = path.join(OUT, ...rel.split('/'));
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, data);
}

const size = [...files.values()].reduce((n, d) => n + Buffer.byteLength(d), 0);
const components = [...files.keys()].filter((f) => f.endsWith('.dc.html')).length;
console.log(`Built ${files.size} files (${(size / 1e6).toFixed(1)} MB, ${components} components) into ${path.relative(ROOT, OUT) || '.'}/`);
for (const w of warnings) console.warn(`warning: ${w}`);
